version: "3.8"
services:
  mariadb:
    container_name: mariadb_container
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: adminpass
      MYSQL_USER: "oksana"
      MYSQL_PASSWORD: "oksanapwd"
    ports:
      - "3306:3306"
    volumes:
      - "~/dockerData/symfony/mariadb/data:/var/lib/mysql/data/"
      - "~/dockerData/symfony/mariadb/logs:/var/lib/mysql/logs/"
    networks:
      - mysql
  phpmyadmin:
    container_name: pma_container
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql
    volumes:
      - "phpmyadmin:/var/lib/phpmyadmin"
networks:
  mysql:
    driver: bridge
volumes:
  phpmyadmin:
