controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
blog_list: 
  path: /
  controller: App\Controller\PostController::list

create_new: 
  path: /new
  controller: App\Controller\PostController::createPost

delete_post: 
  path: /delete/{id}
  controller: App\Controller\PostController::deletePost
# api_post_show:
#     path:       /api/posts/{id}
#     controller: App\Controller\PostController::show
#     methods:    GET|HEAD

edit_post:
    path:       /edit/{id}
    controller: App\Controller\PostController::editPost
